services:
  api:
    build:
      context: ./api
      target: frankenphp_prod
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MAILER_DSN: ${MAILER_DSN}
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}

  frontend:
    build:
      context: ./frontend
      target: prod

  database:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
