services:
  api:
    build:
      target: frankenphp_dev
    volumes:
      - ./api:/app
      - /app/var
      - ./api/frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      FRONTEND_UPSTREAM: frontend:3000
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
      MAILER_DSN: ${MAILER_DSN}
    tty: true

  frontend:
    build:
      target: dev
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://api/core-api

  database:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025"
      - "1080"
