services:
  api:
    build:
      context: ./api
      target: frankenphp_dev
    volumes:
      - ./api:/app
      - /app/var
      - .:/workspace:cached
      - ./api/frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro 
      - ./api/frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      MAILER_DSN: smtp://localhost:1025
    extra_hosts:
      - host.docker.internal:host-gateway
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
      - .:/workspace:cached
    environment:
      WATCHPACK_POLLING: "true"
    stdin_open: true
    tty: true

  database:
    ports:
      - target: 5432
        published: ${DATABASE_PORT:-5432}
        protocol: tcp

  mailer:
    image: schickling/mailcatcher
    ports:
      - "${MAILER_SMTP_PORT:-1025}:1025"
      - "${MAILER_WEB_PORT:-44949}:1080"
