services:
  api:
    build:
      context: ./api
      target: frankenphp_dev
    volumes:
      - ./api:/app
      - /app/var
      - ./api/frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro 
      - ./api/frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      - host.docker.internal:host-gateway
    tty: true

  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
    environment:
      API_PLATFORM_CREATE_CLIENT_ENTRYPOINT: http://api
      API_PLATFORM_CREATE_CLIENT_OUTPUT: .
      WATCHPACK_POLLING: "true"

  database:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "44949:1080"
