services:
  frontend:
    build:
      target: dev
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_ENTRYPOINT: http://api
      NEXT_PUBLIC_API_URL: http://api
      API_PLATFORM_CREATE_CLIENT_ENTRYPOINT: http://api

  api:
    build:
      target: frankenphp_dev
    volumes:
      - ./api:/app
      - /app/var
      - ./api/frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      FRONTEND_UPSTREAM: frontend:3000
    tty: true

  database:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025"
      - "1080"
