<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251125082309 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add issue_tag table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE issue_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, issue_id INT DEFAULT NULL, tag_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8C0D6ABE5E7AA58C ON issue_tag (issue_id)');
        $this->addSql('CREATE INDEX IDX_8C0D6ABEBAD26311 ON issue_tag (tag_id)');
        $this->addSql('ALTER TABLE issue_tag ADD CONSTRAINT FK_8C0D6ABE5E7AA58C FOREIGN KEY (issue_id) REFERENCES issue (id)');
        $this->addSql('ALTER TABLE issue_tag ADD CONSTRAINT FK_8C0D6ABEBAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id)');
        $this->addSql('ALTER TABLE tag DROP CONSTRAINT fk_389b7835e7aa58c');
        $this->addSql('DROP INDEX idx_389b7835e7aa58c');
        $this->addSql('ALTER TABLE tag ADD text_color VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE tag DROP issue_id');
        $this->addSql('ALTER TABLE tag RENAME COLUMN color TO background_color');
        $this->addSql('CREATE INDEX idx_tag_title ON tag (title)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE issue_tag DROP CONSTRAINT FK_8C0D6ABE5E7AA58C');
        $this->addSql('ALTER TABLE issue_tag DROP CONSTRAINT FK_8C0D6ABEBAD26311');
        $this->addSql('DROP TABLE issue_tag');
        $this->addSql('DROP INDEX idx_tag_title');
        $this->addSql('ALTER TABLE tag ADD issue_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE tag ADD color VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE tag DROP background_color');
        $this->addSql('ALTER TABLE tag DROP text_color');
        $this->addSql('ALTER TABLE tag ADD CONSTRAINT fk_389b7835e7aa58c FOREIGN KEY (issue_id) REFERENCES issue (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_389b7835e7aa58c ON tag (issue_id)');
    }
}
