<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250829093046 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create initial tables and relationships';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE attachment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, path VARCHAR(255) NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, issue_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_795FD9BB5E7AA58C ON attachment (issue_id)');
        $this->addSql('CREATE TABLE chat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE chat_member (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, chat_id INT DEFAULT NULL, member_id INT DEFAULT NULL, role_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1738CD591A9A7125 ON chat_member (chat_id)');
        $this->addSql('CREATE INDEX IDX_1738CD597597D3FE ON chat_member (member_id)');
        $this->addSql('CREATE INDEX IDX_1738CD59D60322AC ON chat_member (role_id)');
        $this->addSql('CREATE TABLE chat_role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN NOT NULL, issue_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9474526C5E7AA58C ON comment (issue_id)');
        $this->addSql('CREATE TABLE issue (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, estimated INT DEFAULT NULL, logged_time INT DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, priority VARCHAR(255) NOT NULL, status_id INT NOT NULL, type_id INT NOT NULL, resolution_id INT DEFAULT NULL, project_id INT DEFAULT NULL, reporter_id INT DEFAULT NULL, parent_issue_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_12AD233E6BF700BD ON issue (status_id)');
        $this->addSql('CREATE INDEX IDX_12AD233EC54C8C93 ON issue (type_id)');
        $this->addSql('CREATE INDEX IDX_12AD233E12A1C43A ON issue (resolution_id)');
        $this->addSql('CREATE INDEX IDX_12AD233E166D1F9C ON issue (project_id)');
        $this->addSql('CREATE INDEX IDX_12AD233EE1CFE6F5 ON issue (reporter_id)');
        $this->addSql('CREATE INDEX IDX_12AD233EC1B7095D ON issue (parent_issue_id)');
        $this->addSql('CREATE TABLE issue_user (issue_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY(issue_id, user_id))');
        $this->addSql('CREATE INDEX IDX_D5741E855E7AA58C ON issue_user (issue_id)');
        $this->addSql('CREATE INDEX IDX_D5741E85A76ED395 ON issue_user (user_id)');
        $this->addSql('CREATE TABLE issue_issue (issue_source INT NOT NULL, issue_target INT NOT NULL, PRIMARY KEY(issue_source, issue_target))');
        $this->addSql('CREATE INDEX IDX_80274A6DAD7AF554 ON issue_issue (issue_source)');
        $this->addSql('CREATE INDEX IDX_80274A6DB49FA5DB ON issue_issue (issue_target)');
        $this->addSql('CREATE TABLE issue_sprint (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, added_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, archived_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_in_sprint BOOLEAN NOT NULL, issue_id INT DEFAULT NULL, sprint_id INT DEFAULT NULL, archived_by_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1D70DF905E7AA58C ON issue_sprint (issue_id)');
        $this->addSql('CREATE INDEX IDX_1D70DF908C24077B ON issue_sprint (sprint_id)');
        $this->addSql('CREATE INDEX IDX_1D70DF9077BE2925 ON issue_sprint (archived_by_id)');
        $this->addSql('CREATE TABLE issue_status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE issue_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE organization (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE organization_member (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_blocked BOOLEAN NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, member_id INT DEFAULT NULL, organization_id INT DEFAULT NULL, role_id INT DEFAULT NULL, invited_by_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_756A2A8D7597D3FE ON organization_member (member_id)');
        $this->addSql('CREATE INDEX IDX_756A2A8D32C8A3DE ON organization_member (organization_id)');
        $this->addSql('CREATE INDEX IDX_756A2A8DD60322AC ON organization_member (role_id)');
        $this->addSql('CREATE INDEX IDX_756A2A8DA7B4A7E3 ON organization_member (invited_by_id)');
        $this->addSql('CREATE TABLE organization_role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, is_archived BOOLEAN NOT NULL, organization_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2FB3D0EE32C8A3DE ON project (organization_id)');
        $this->addSql('CREATE TABLE project_member (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_blocked BOOLEAN NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, member_id INT DEFAULT NULL, project_id INT DEFAULT NULL, invited_by_id INT DEFAULT NULL, role_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_674011327597D3FE ON project_member (member_id)');
        $this->addSql('CREATE INDEX IDX_67401132166D1F9C ON project_member (project_id)');
        $this->addSql('CREATE INDEX IDX_67401132A7B4A7E3 ON project_member (invited_by_id)');
        $this->addSql('CREATE INDEX IDX_67401132D60322AC ON project_member (role_id)');
        $this->addSql('CREATE TABLE project_role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE resolution (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE sprint (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, goal TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(255) NOT NULL, is_archived BOOLEAN NOT NULL, created_by_id INT NOT NULL, project_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EF8055B7B03A8386 ON sprint (created_by_id)');
        $this->addSql('CREATE INDEX IDX_EF8055B7166D1F9C ON sprint (project_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, color VARCHAR(255) DEFAULT NULL, issue_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_389B7835E7AA58C ON tag (issue_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, registered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE attachment ADD CONSTRAINT FK_795FD9BB5E7AA58C FOREIGN KEY (issue_id) REFERENCES issue (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chat_member ADD CONSTRAINT FK_1738CD591A9A7125 FOREIGN KEY (chat_id) REFERENCES chat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chat_member ADD CONSTRAINT FK_1738CD597597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chat_member ADD CONSTRAINT FK_1738CD59D60322AC FOREIGN KEY (role_id) REFERENCES chat_role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C5E7AA58C FOREIGN KEY (issue_id) REFERENCES issue (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue ADD CONSTRAINT FK_12AD233E6BF700BD FOREIGN KEY (status_id) REFERENCES issue_status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue ADD CONSTRAINT FK_12AD233EC54C8C93 FOREIGN KEY (type_id) REFERENCES issue_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue ADD CONSTRAINT FK_12AD233E12A1C43A FOREIGN KEY (resolution_id) REFERENCES resolution (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue ADD CONSTRAINT FK_12AD233E166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue ADD CONSTRAINT FK_12AD233EE1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue ADD CONSTRAINT FK_12AD233EC1B7095D FOREIGN KEY (parent_issue_id) REFERENCES issue (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue_user ADD CONSTRAINT FK_D5741E855E7AA58C FOREIGN KEY (issue_id) REFERENCES issue (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue_user ADD CONSTRAINT FK_D5741E85A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue_issue ADD CONSTRAINT FK_80274A6DAD7AF554 FOREIGN KEY (issue_source) REFERENCES issue (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue_issue ADD CONSTRAINT FK_80274A6DB49FA5DB FOREIGN KEY (issue_target) REFERENCES issue (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue_sprint ADD CONSTRAINT FK_1D70DF905E7AA58C FOREIGN KEY (issue_id) REFERENCES issue (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue_sprint ADD CONSTRAINT FK_1D70DF908C24077B FOREIGN KEY (sprint_id) REFERENCES sprint (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue_sprint ADD CONSTRAINT FK_1D70DF9077BE2925 FOREIGN KEY (archived_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization_member ADD CONSTRAINT FK_756A2A8D7597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization_member ADD CONSTRAINT FK_756A2A8D32C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization_member ADD CONSTRAINT FK_756A2A8DD60322AC FOREIGN KEY (role_id) REFERENCES organization_role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization_member ADD CONSTRAINT FK_756A2A8DA7B4A7E3 FOREIGN KEY (invited_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE32C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_member ADD CONSTRAINT FK_674011327597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_member ADD CONSTRAINT FK_67401132166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_member ADD CONSTRAINT FK_67401132A7B4A7E3 FOREIGN KEY (invited_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_member ADD CONSTRAINT FK_67401132D60322AC FOREIGN KEY (role_id) REFERENCES project_role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sprint ADD CONSTRAINT FK_EF8055B7B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sprint ADD CONSTRAINT FK_EF8055B7166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tag ADD CONSTRAINT FK_389B7835E7AA58C FOREIGN KEY (issue_id) REFERENCES issue (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE attachment DROP CONSTRAINT FK_795FD9BB5E7AA58C');
        $this->addSql('ALTER TABLE chat_member DROP CONSTRAINT FK_1738CD591A9A7125');
        $this->addSql('ALTER TABLE chat_member DROP CONSTRAINT FK_1738CD597597D3FE');
        $this->addSql('ALTER TABLE chat_member DROP CONSTRAINT FK_1738CD59D60322AC');
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526C5E7AA58C');
        $this->addSql('ALTER TABLE issue DROP CONSTRAINT FK_12AD233E6BF700BD');
        $this->addSql('ALTER TABLE issue DROP CONSTRAINT FK_12AD233EC54C8C93');
        $this->addSql('ALTER TABLE issue DROP CONSTRAINT FK_12AD233E12A1C43A');
        $this->addSql('ALTER TABLE issue DROP CONSTRAINT FK_12AD233E166D1F9C');
        $this->addSql('ALTER TABLE issue DROP CONSTRAINT FK_12AD233EE1CFE6F5');
        $this->addSql('ALTER TABLE issue DROP CONSTRAINT FK_12AD233EC1B7095D');
        $this->addSql('ALTER TABLE issue_user DROP CONSTRAINT FK_D5741E855E7AA58C');
        $this->addSql('ALTER TABLE issue_user DROP CONSTRAINT FK_D5741E85A76ED395');
        $this->addSql('ALTER TABLE issue_issue DROP CONSTRAINT FK_80274A6DAD7AF554');
        $this->addSql('ALTER TABLE issue_issue DROP CONSTRAINT FK_80274A6DB49FA5DB');
        $this->addSql('ALTER TABLE issue_sprint DROP CONSTRAINT FK_1D70DF905E7AA58C');
        $this->addSql('ALTER TABLE issue_sprint DROP CONSTRAINT FK_1D70DF908C24077B');
        $this->addSql('ALTER TABLE issue_sprint DROP CONSTRAINT FK_1D70DF9077BE2925');
        $this->addSql('ALTER TABLE organization_member DROP CONSTRAINT FK_756A2A8D7597D3FE');
        $this->addSql('ALTER TABLE organization_member DROP CONSTRAINT FK_756A2A8D32C8A3DE');
        $this->addSql('ALTER TABLE organization_member DROP CONSTRAINT FK_756A2A8DD60322AC');
        $this->addSql('ALTER TABLE organization_member DROP CONSTRAINT FK_756A2A8DA7B4A7E3');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EE32C8A3DE');
        $this->addSql('ALTER TABLE project_member DROP CONSTRAINT FK_674011327597D3FE');
        $this->addSql('ALTER TABLE project_member DROP CONSTRAINT FK_67401132166D1F9C');
        $this->addSql('ALTER TABLE project_member DROP CONSTRAINT FK_67401132A7B4A7E3');
        $this->addSql('ALTER TABLE project_member DROP CONSTRAINT FK_67401132D60322AC');
        $this->addSql('ALTER TABLE sprint DROP CONSTRAINT FK_EF8055B7B03A8386');
        $this->addSql('ALTER TABLE sprint DROP CONSTRAINT FK_EF8055B7166D1F9C');
        $this->addSql('ALTER TABLE tag DROP CONSTRAINT FK_389B7835E7AA58C');
        $this->addSql('DROP TABLE attachment');
        $this->addSql('DROP TABLE chat');
        $this->addSql('DROP TABLE chat_member');
        $this->addSql('DROP TABLE chat_role');
        $this->addSql('DROP TABLE comment');
        $this->addSql('DROP TABLE issue');
        $this->addSql('DROP TABLE issue_user');
        $this->addSql('DROP TABLE issue_issue');
        $this->addSql('DROP TABLE issue_sprint');
        $this->addSql('DROP TABLE issue_status');
        $this->addSql('DROP TABLE issue_type');
        $this->addSql('DROP TABLE organization');
        $this->addSql('DROP TABLE organization_member');
        $this->addSql('DROP TABLE organization_role');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE project_member');
        $this->addSql('DROP TABLE project_role');
        $this->addSql('DROP TABLE resolution');
        $this->addSql('DROP TABLE sprint');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE "user"');
    }
}
