<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251203084247 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add RoleChangeLog entity to track role changes across entities';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE role_change_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entity_type VARCHAR(255) NOT NULL, entity_id INT NOT NULL, old_role VARCHAR(255) DEFAULT NULL, new_role VARCHAR(255) NOT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, member_id INT NOT NULL, changed_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D12E60F47597D3FE ON role_change_log (member_id)');
        $this->addSql('CREATE INDEX IDX_D12E60F4828AD0A0 ON role_change_log (changed_by_id)');
        $this->addSql('ALTER TABLE role_change_log ADD CONSTRAINT FK_D12E60F47597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE role_change_log ADD CONSTRAINT FK_D12E60F4828AD0A0 FOREIGN KEY (changed_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE role_change_log DROP CONSTRAINT FK_D12E60F47597D3FE');
        $this->addSql('ALTER TABLE role_change_log DROP CONSTRAINT FK_D12E60F4828AD0A0');
        $this->addSql('DROP TABLE role_change_log');
    }
}
