<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251002065345 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add ProjectSequence entity and name_abbreviation field to Project entity';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE project_sequence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, last_issue_number INT DEFAULT NULL, project_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6FC85CF0166D1F9C ON project_sequence (project_id)');
        $this->addSql('ALTER TABLE project_sequence ADD CONSTRAINT FK_6FC85CF0166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project ADD name_abbreviation VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE project_sequence DROP CONSTRAINT FK_6FC85CF0166D1F9C');
        $this->addSql('DROP TABLE project_sequence');
        $this->addSql('ALTER TABLE project DROP name_abbreviation');
    }
}
