<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251207160618 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add issue_calendar_event table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE issue_calendar_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(50) NOT NULL, external_event_id VARCHAR(255) NOT NULL, external_html_link VARCHAR(255) DEFAULT NULL, last_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, issue_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AF49CD1E5E7AA58C ON issue_calendar_event (issue_id)');
        $this->addSql('ALTER TABLE issue_calendar_event ADD CONSTRAINT FK_AF49CD1E5E7AA58C FOREIGN KEY (issue_id) REFERENCES issue (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE issue_calendar_event DROP CONSTRAINT FK_AF49CD1E5E7AA58C');
        $this->addSql('DROP TABLE issue_calendar_event');
    }
}
