<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251128102922 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create user_oauth table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_oauth (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(255) NOT NULL, provider_id VARCHAR(255) NOT NULL, access_token TEXT DEFAULT NULL, refresh_token TEXT DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E618839CA76ED395 ON user_oauth (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROVIDER_ID ON user_oauth (provider, provider_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROVIDER_USER ON user_oauth (provider, user_id)');
        $this->addSql('ALTER TABLE user_oauth ADD CONSTRAINT FK_E618839CA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tag ALTER is_archived DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE user_oauth DROP CONSTRAINT FK_E618839CA76ED395');
        $this->addSql('DROP TABLE user_oauth');
        $this->addSql('ALTER TABLE tag ALTER is_archived SET DEFAULT false');
    }
}
